### ISSUE TITLE
Feedback getting started

### ISSUE THREAD

**Issue by poi33** [enonic/doc-intro-to-enonic#28]
https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/setup.adoc#L10
you can also `use use` the terminal

Setup.adoc **Enonic CLI**: Could we mention that they are installing the cli when running the different commands? Currently it is just `run the following commands`. 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/setup.adoc#L140
Unclear about this sentence: `designed specifically for writing computer code.`

Sandboxes.adoc **Admin console** Can we mention that the admin menu items can have different names in different langauges. Since we translate them`? 

Apps.adoc **building and deploying** I think users might stop the running server deploy then start the running server again. Could we add something about having two terminals open? One for the server and one for deploying the app? 

Content.adoc **Task: The artist content type** We are using screen shots and talking about content studio before any introduction or mention of it previusly? Do we assume they know what it is or should be mention this before giving a task about it?

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/content.adoc#L23
Does the starter really not include this directory? Should it not do that? Even if its included we should mention the folder structure. 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/content.adoc#L24
We should not skip the creation of the `artist` folder. You need to pay close attention to notice that a folder was added to the path. 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/content.adoc#L76
`Command bar`? Is it not just called Toolbar? https://developer.enonic.com/docs/content-studio/stable/navigator#toolbar 

Should we mention the save keyboard shortcut too? This is maybe the only keyboard shortcut i use alot. 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/content.adoc#L112
I'm unsure about using folder to create a hierarki. Is it not bad practice to setup a page strcuture with folders?

( Too be continued only to chapter 4 so far)

**Comment by thomasheartman** [comment]
Regarding the missing content-types directory: yes, the starter really doesn't include it. I agree that it might make sense to have it included by default, though. I guess: open an issue for it on the starter repo? On the other hand, this probably goes for most (all?) contentless starters, so maybe start a discussion somewhere?

As for the other issues you raise: working on addressing them at the moment.

**Comment by thomasheartman** [comment]
Created a [PR that addresses most of the changes here](https://github.com/enonic/doc-getting-started/pull/29).

The only one I haven't addressed is the one about using folders for creating a hierarchy. I too seem to remember hearing that using folders isn't ideal, but it was the only solution I found, and tsi hasn't said anything 🤷 Is there a better solution that's built into CS? What _is_ the recommended way to create hierarchy?

**Comment by poi33** [comment]
I don't think we have a recommended way. Its up to how the company likes the organize and how the site is coded. 
But when it comes to headless it is really not important how the structure is 🤷

**Comment by poi33** [comment]
Continuation from chapter 4:
**Headless api** 
https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/headless-api.adoc#L80
`let's look writing` ? 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/headless-api.adoc#L323
`which comes which comes`

**input types** I don't think new users will remember what an inpute type is a the start of the chapter. Can we remind them in some way? 

**occurences**
https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/input-types.adoc#L68
This is a bit confusing. Because the values can not be controlled. If only a single value is present then it can never be a list. 
Ofc if we are only talking about the front-end then it will be displayed like a list or a single value based on the occurrences. 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/input-types.adoc#L103
The richt text editor link goes to the same doc? and the # query param is not in current doc?

(Too be continued in chapter 8)

**Comment by poi33** [comment]
https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/rich-text.adoc#L24

Text tools, rich text controls,input appearance. Are they all the same thing? Docs just call it Toolbar elements. Text tools makes the most sence to me, since its in the toolbar. 

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/rich-text.adoc#L69
We need to link to full configuration list / html area docs here. Something like for all configuration options look here(link)?

https://github.com/enonic/doc-getting-started/blob/a13f82de45c383a6bcd884e68eceb9eeed7f0db1/docs/rich-text.adoc#L210
`that we added the added the image`?
